import {$,$$,E,get,post,icon,button,badge,stats,pageHead,empty,listen,toast,modal,showJSON,
        runJob,download,artifactsHTML,bindArtifacts,pickPath,bytes,when,fileIcon,dropZone,bindDrop,jobsHTML,bindJobs,mount} from './common.js';
const info=await get('info');
let state,selectedId=null,tab='review',rectangles=[],enabled=null,literals='',useOCR=false,pdfPage=1,pdfRectangles={};
const guide=`<p>DataClean Room creates a new copy. It never changes the input.</p><ol class="list-note"><li>Scan a file or paste text.</li><li>Read the findings and coverage notes.</li><li>Review the text replacement or select image regions.</li><li>Create a clean copy and inspect it before sharing.</li></ol><p>Pattern detection can miss private information. PDF exports rebuild page pixels. Office exports rebuild visible text and cells. Neither export copies source attachments or macros. Review layout and omissions before sharing.</p>`;
async function refresh(){state=await get('state');if(enabled===null)enabled=Object.keys(state.kinds);}
function options(){return {enabled,literals:literals.split('\n').map(x=>x.trim()).filter(Boolean),ocr:useOCR};}
async function scanPaths(paths){const r=await runJob('scan',{paths,...options()});selectedId=r.scans.find(s=>s.report.export_mode==='text')?.id||r.scans[0]?.id;rectangles=[];pdfPage=1;pdfRectangles={};await refresh();if(tab==='review')await renderReview();else location.hash='review';toast('Scan complete. Review the findings and coverage notes.');}
async function demo(){await scanPaths((await get('examples')).files);}
const metrics=()=>stats([['Scanned files',state.stats.files,'Most recent 100 files','file'],['Review findings',state.stats.findings,'Patterns and metadata fields','search'],['Clean copies',state.stats.copies,'Inputs stay unchanged','copy']]);
async function renderReview(){
 if(!state.entries.some(e=>e.id===selectedId))selectedId=state.entries[0]?.id;
 $('#view').innerHTML=pageHead('LOCAL PRIVACY WORKSPACE','Share a copy. Keep control.','Find private patterns, remove metadata, and review exactly what the output will contain.',button('paste-text','Paste text','file','secondary')+button('demo-files','Use sample files','play','primary'))+metrics()+
 `<div class="notice warning">${icon('shield')}<span>Review is required. A clean-copy export is not proof that all private information was removed.</span></div>`+dropZone('privacy-drop')+
 `<div class="split wide-detail"><section class="panel"><div class="panel-head"><h2>Scan queue</h2>${button('choose-file','Choose file','folder','ghost')}</div><div id="scan-queue">${state.entries.length?state.entries.map(e=>`<button class="file-row ${e.id===selectedId?'selected':''}" data-scan="${E(e.id)}">${fileIcon(e.name)}<span class="file-main"><strong>${E(e.name)}</strong><small>${bytes(e.size)} · ${E(e.export_mode)} export</small><span class="inline-meta">${badge((e.findings||0)+' findings',e.findings?'warn':'')}${e.output?badge('Copy created','good'):badge('Review required','warn')}</span></span>${icon('arrow')}</button>`).join(''):empty('No files scanned','Use the sample files or choose a file from your PC.','shield')}</div></section><section class="panel"><div class="panel-head"><h2>Review and export</h2><span id="review-mode"></span></div><div id="scan-detail" class="panel-body"></div></section></div>`;
 listen('#demo-files','click',demo);listen('#paste-text','click',pasteDialog);listen('#choose-file','click',async()=>{const path=await pickPath(info.example_path,true);if(path)await scanPaths([path]);});bindDrop('privacy-drop',files=>scanPaths(files.map(f=>f.path)));
 listen('[data-scan]','click',async(_,node)=>{selectedId=node.dataset.scan;rectangles=[];pdfPage=1;pdfRectangles={};$$('[data-scan]').forEach(n=>n.classList.toggle('selected',n.dataset.scan===selectedId));await renderDetail();});await renderDetail();
}
async function pasteDialog(){const dialog=modal('Scan pasted text',`<label class="field">Text<textarea id="pasted-text" rows="10" maxlength="250000" placeholder="Paste the text you plan to share."></textarea></label><p class="hint">The text is saved in this app's private local inbox. Delete that folder when it is no longer needed.</p>`,button('scan-paste','Scan text','search','primary'));listen('#scan-paste','click',async()=>{const text=$('#pasted-text').value;dialog.close();const r=await runJob('paste',{text,...options()});selectedId=r.scans[0]?.id;await refresh();await renderReview();});}
async function renderDetail(){
 if(!selectedId){$('#scan-detail').innerHTML=empty('Select a scan','Review the source, findings, and output here.','shield');return;}
 const entry=await get('scan',{id:selectedId,preview:'1'}),r=entry.report;
 if(tab!=='review'||!$('#scan-detail'))return;
 $('#review-mode').innerHTML=badge(r.export_mode==='text'?'New plain-text file':r.export_mode==='image'?'New PNG image':r.export_mode==='archive'?'New ZIP bundle':r.export_mode==='pdf'?'New raster PDF':r.export_mode==='office'?'Rebuilt Office copy':'Unsupported','accent');
 const metadata=(r.metadata||[]).map(m=>`<li>${E(m.label||m.kind||m.type||m.name||JSON.stringify(m))}</li>`).join('');
 $('#scan-detail').innerHTML=`<div class="row-between"><div><h2>${E(r.name)}</h2><p class="small muted">${bytes(r.size)} · ${E(r.format)} · ${r.findings} review findings</p></div>${button('scan-report','Report','download','ghost')}</div><div class="inline-meta">${Object.entries(r.counts||{}).map(([k,v])=>badge(`${state.kinds[k]||k}: ${v}`,'warn')).join(' ')}${r.metadata?.length?badge(r.metadata.length+' metadata fields','warn'):''}</div>
 <div class="coverage-notes"><h3>What the scan checked</h3><p class="small muted">${E((r.coverage||[]).join('. '))}</p><details ${r.export_mode==='text'?'':'open'}><summary>Coverage limits and warnings (${r.warnings.length})</summary><ul class="list-note">${r.warnings.map(w=>`<li>${E(w)}</li>`).join('')}</ul></details>${metadata?`<details><summary>Metadata fields</summary><ul class="list-note">${metadata}</ul></details>`:''}</div>
 <div id="content-review"></div>${r.supported?`<div class="export-controls"><label class="field">Text replacement<select id="replace-mode"><option value="labels">Labels, such as [EMAIL_1]</option><option value="blocks">One label: [REDACTED]</option></select></label>${r.truncated?'<label class="checkbox"><input type="checkbox" id="accept-partial"> I accept an incomplete plain-text export. Unextracted content will not be included.</label>':''}<div class="notice small">${r.export_mode==='text'?'The export is a new UTF-8 text file. Formatting and source attachments are not included.':r.export_mode==='image'?'Selected regions and enabled OCR findings are redacted. Check the remaining visible pixels.':r.export_mode==='pdf'?'Matched text and selected regions are painted into new PDF page pixels. Original text, forms, and attachments are discarded.':r.export_mode==='office'?'The output rebuilds visible text and cells. Source graphics, comments, macros, formulas, and hidden parts are not retained.':'Unsupported entries are excluded. PNG pixels remain visible.'}</div>${button('create-copy','Create clean copy','shield','primary')}</div>`:''}<div id="clean-output">${entry.output?outputHTML(entry.output):''}</div>`;
 listen('#scan-report','click',async()=>download(await post('export-report',{id:selectedId})));
 if(r.export_mode==='text'||r.export_mode==='office'){
  $('#content-review').innerHTML=`<div class="two-cols text-comparison"><div><p class="compare-title">Source text</p><pre class="preview-text" id="source-text">${E(r.text||'No text was extracted.')}</pre></div><div><p class="compare-title">Clean copy preview</p><pre class="preview-text" id="clean-preview">${E(r.preview||'No text was extracted.')}</pre></div></div>`;
  listen('#replace-mode','change',()=>{$('#clean-preview').textContent=$('#replace-mode').value==='blocks'?(r.preview||'').replace(/\[(?:EMAIL|PHONE|CNIC|CARD|IPV4|IBAN|NAME|ADDRESS|CUSTOM)_\d+\]/g,'[REDACTED]'):r.preview;});
 }else if(r.export_mode==='image'||r.export_mode==='pdf')await renderImage(r);
 else if(r.export_mode==='archive')$('#content-review').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Archive member</th><th>Export</th><th>Findings</th></tr></thead><tbody>${r.members.map(m=>`<tr><td><strong>${E(m.name)}</strong><small>${E(m.note)}</small></td><td>${badge(m.supported?m.export:'Excluded',m.supported?'':'warn')}</td><td>${m.matches+m.metadata}</td></tr>`).join('')}</tbody></table></div>`;
 else $('#content-review').innerHTML=empty('No implemented export','The app will not pass this file through as a clean copy.','alert');
 if(r.supported)listen('#create-copy','click',async()=>{if(r.export_mode==='pdf')pdfRectangles[pdfPage]=rectangles.map(x=>x.slice());const page_rectangles=Object.entries(pdfRectangles).flatMap(([page,items])=>items.map(rect=>({page:Number(page),rect})));const id=selectedId,result=await runJob('sanitize',{id,mode:$('#replace-mode').value,rectangles,page_rectangles,accept_partial:$('#accept-partial')?.checked||false});await refresh();if(tab==='review'&&selectedId===id){$('.stats').outerHTML=metrics();$('#clean-output').innerHTML=outputHTML(result);bindOutput(result);}toast('A new copy was created. Inspect it before sharing.');});
 if(entry.output)bindOutput(entry.output);
}
function outputHTML(output){return `<div class="status-banner"><div>${icon('check')}<strong>New copy created</strong></div>${badge(output.audit.original_unchanged?'Source unchanged':'Check source','good')}</div>${artifactsHTML([output.output,output.report])}<p class="small muted">The audit report lists the operations and limits. It does not certify that sharing is safe.</p>`;}
function bindOutput(output){bindArtifacts([output.output,output.report],$('#clean-output'));}
async function renderImage(report){
 $('#content-review').innerHTML=`<p class="compare-title">${report.export_mode==='pdf'?'PDF page review':'Image review'}</p>${report.export_mode==='pdf'?`<label>Page<select id="pdf-page">${report.pages.map(p=>`<option value="${p.page}" ${p.page===pdfPage?'selected':''}>Page ${p.page}</option>`).join('')}</select></label><p class="small muted">Detected text regions are redacted automatically. Manual regions add masks for visible data that patterns miss. Select each page before exporting.</p>`:''}<p class="small muted">${info.capabilities.images?'Drag over private text or faces to select opaque black rectangles.':'Install Pillow for pixel redaction. The core PNG export removes metadata only.'}</p><div class="image-editor"><canvas id="image-canvas" aria-label="Image preview and redaction region selector"></canvas></div><div class="section-actions"><span id="region-count" class="small muted">${rectangles.length} selected regions</span>${button('undo-region','Undo region','','ghost')}${button('clear-regions','Clear regions','','ghost')}${info.capabilities.images?button('add-region','Add coordinates','plus','secondary'):''}</div>`;
 const result=await get('image',{id:selectedId,page:pdfPage});const canvas=$('#image-canvas');if(!canvas)return;
 const im=new Image();im.src=`data:${result.mime};base64,${result.data}`;await im.decode();canvas.width=im.width;canvas.height=im.height;const ctx=canvas.getContext('2d');let start=null,drag=null;
 const draw=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0);for(const [a,b,c,d]of rectangles){ctx.fillStyle='#000';ctx.fillRect(a,b,c-a,d-b);}if(start&&drag){ctx.fillStyle='#0009';ctx.fillRect(start.x,start.y,drag.x-start.x,drag.y-start.y);}$('#region-count').textContent=rectangles.length+' selected regions';};
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,Math.round((e.clientX-r.left)*canvas.width/r.width))),y:Math.max(0,Math.min(canvas.height,Math.round((e.clientY-r.top)*canvas.height/r.height)))};};
 if(info.capabilities.images){canvas.addEventListener('pointerdown',e=>{start=point(e);drag=start;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(start){drag=point(e);draw();}});canvas.addEventListener('pointerup',e=>{if(!start)return;drag=point(e);const r=[Math.min(start.x,drag.x),Math.min(start.y,drag.y),Math.max(start.x,drag.x),Math.max(start.y,drag.y)];if(r[2]>r[0]&&r[3]>r[1])rectangles.push(r);start=drag=null;draw();});canvas.addEventListener('pointercancel',()=>{start=drag=null;draw();});}
 listen('#pdf-page','change',async()=>{pdfRectangles[pdfPage]=rectangles.map(x=>x.slice());pdfPage=Number($('#pdf-page').value);rectangles=(pdfRectangles[pdfPage]||[]).map(x=>x.slice());await renderImage(report);});
 listen('#undo-region','click',()=>{rectangles.pop();draw();});listen('#clear-regions','click',()=>{rectangles=[];draw();});
 listen('#add-region','click',()=>{const d=modal('Add a pixel region',`<p class="muted small">Image size: ${canvas.width} × ${canvas.height}. The right and bottom edges are excluded.</p><div class="two-cols">${['Left','Top','Right','Bottom'].map((label,i)=>`<label class="field">${label}<input id="coord-${i}" type="number" min="0" value="${i>1?50:0}"></label>`).join('')}</div>`,button('save-region','Add region','plus','primary'));listen('#save-region','click',()=>{const r=[0,1,2,3].map(i=>Number($('#coord-'+i).value));if(!r.every(Number.isInteger)||r[0]<0||r[1]<0||r[2]>canvas.width||r[3]>canvas.height||r[0]>=r[2]||r[1]>=r[3])throw Error('Enter valid pixel coordinates within the image.');rectangles.push(r);d.close();draw();});});draw();
}
async function renderRules(){
 const notes={email:'Structured email address patterns.',phone:'Phone-like text can include harmless numbers.',cnic:'Formatted 5-7-1 digit identifiers.',card:'13 to 19 digits with a valid Luhn checksum.',ipv4:'Valid four-part IPv4 addresses.',iban:'IBAN length and checksum checks.',name:'Names after labels such as Name: or Patient:.',address:'Addresses after labels such as Address:.',custom:'Exact text values. Matching ignores letter case.'};
 $('#view').innerHTML=pageHead('SCAN RULES','Choose what needs review.','These controls apply to new scans. Existing scans keep the rules used when they were created.')+`<section class="panel"><div class="panel-body"><div class="rule-grid">${Object.entries(state.kinds).map(([k,label])=>`<label class="rule-card"><input type="checkbox" data-rule="${k}" ${enabled.includes(k)?'checked':''}><span><strong>${E(label)}</strong><small>${E(notes[k])}</small></span></label>`).join('')}</div><label class="field">Custom private text, one value per line<textarea id="private-literals" rows="5" placeholder="Project Cedar\nAn unlabelled personal name">${E(literals)}</textarea></label><p class="hint">Up to 30 values, each up to 200 characters. Custom values are private data. Scan records keep them locally.</p><label class="checkbox"><input type="checkbox" id="enable-ocr" ${useOCR?'checked':''} ${!info.capabilities.ocr?'disabled':''}> Use installed local Tesseract OCR for images and scanned PDF pages</label><p class="hint">${info.capabilities.ocr?'OCR can miss text. Image exports still need manual review.':'Tesseract was not found. Core text and metadata scans work without it.'}</p>${button('apply-rules','Apply to new scans','check','primary')}</div></section><div class="notice warning">Names, addresses, faces, handwriting, and secrets can escape these checks. Add custom text and inspect every output.</div>`;
 listen('#apply-rules','click',()=>{enabled=$$('[data-rule]:checked').map(n=>n.dataset.rule);literals=$('#private-literals').value;useOCR=$('#enable-ocr').checked;toast('Rules apply to new scans in this session.');});
}
async function renderOutputs(){const entries=state.entries.filter(e=>e.output);$('#view').innerHTML=pageHead('CLEAN COPY HISTORY','Keep the source and the evidence.','Each output has a separate audit report. The app never overwrites the input.')+(entries.length?entries.map((e,i)=>`<section class="panel"><div class="panel-head"><div><h2>${E(e.name)}</h2><span class="small muted">${E(when(e.created))}</span></div>${badge('Review before sharing','warn')}</div><div class="panel-body" id="output-${i}">${artifactsHTML([e.output.output,e.output.report])}</div></section>`).join(''):`<section class="panel">${empty('No clean copies yet','Scan a file and create a reviewed copy.','shield')}</section>`);entries.forEach((e,i)=>bindArtifacts([e.output.output,e.output.report],$('#output-'+i)));}
async function renderCoverage(){const rows=[['Text and code','Decode and detect selected patterns','New plain UTF-8 text','No semantic identity detection'],['DOCX, PPTX, XLSX','Extract text; inspect metadata and hidden parts','Rebuilt Office file','Source graphics, hidden parts, formulas, and formatting are omitted'],['OpenDocument','Extract supported text','New plain text','Source layout is not retained'],['PDF','Native text, optional OCR, manual page regions','New image-only PDF','Original text, forms, attachments, and links are not copied; inspect visible pixels'],['PNG','Chunk metadata, optional OCR','Metadata-stripped PNG; pixel regions with Pillow','Metadata cleaning does not hide visible text'],['JPEG and other Pillow images','Available metadata, optional OCR','New pixel-only PNG with optional regions','Pillow is required for export'],['ZIP','Supported top-level entries','New bundle with generic names','Unsupported entries are excluded; nested archives are not scanned']];$('#view').innerHTML=pageHead('COVERAGE AND LIMITS','Know what the copy contains.','The app reports its limits rather than showing a false safety score.')+`<section class="panel"><div class="panel-body">${guide}</div><div class="table-wrap"><table><thead><tr><th>Input</th><th>Scan</th><th>Output</th><th>Limit</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${E(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panel-head"><h2>Processing jobs</h2></div>${jobsHTML(state.jobs)}</section>`;bindJobs();}
async function route(id){tab=id;await refresh();if(id==='review')await renderReview();else if(id==='rules')await renderRules();else if(id==='outputs')await renderOutputs();else await renderCoverage();}
mount(info,[['review','Scan and review','shield'],['rules','Detection rules','settings'],['outputs','Clean copies','file'],['coverage','Coverage and jobs','help']],route,guide);
